use_default_settings: true
server:
  limiter: false
search:
  safe_search: 1
  formats:
    - html
    - json
enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Self Information
  - Tracker URL remover
