apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentai-local
spec:
  ingressClassName: traefik
  rules:
    - host: coordinator.agentai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coordinator
                port:
                  number: 8000
    - host: admin.agentai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 8002
