apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentai
resources:
  - ../../base
  - telegram-poller.yaml
  - networkpolicy-telegram-poller-egress.yaml
  - networkpolicy-allow-ingress-controller.yaml
  - ingress.yaml
images:
  - name: ghcr.io/manarj789/agentai
    newName: ghcr.io/manarj789/agentai
    newTag: latest
patches:
  - target:
      kind: ConfigMap
      name: agentai-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: dev
